# Generated by Django 5.0.4 on 2024-05-02 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=10)),
                ('tipo', models.CharField(max_length=50)),
                ('ocupado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parqueaderos', models.ManyToManyField(to='parqueadero.parking')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10)),
                ('tipo', models.CharField(max_length=50)),
                ('hora_ingreso', models.DateTimeField(blank=True, null=True)),
                ('parqueadero', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parqueadero_asociado', to='parqueadero.parking')),
            ],
        ),
        migrations.AddField(
            model_name='parking',
            name='vehiculo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parqueadero.vehiculo'),
        ),
    ]
