# Generated by Django 5.0.4 on 2024-05-05 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parqueadero', '0002_vehiculo_hora_salida_delete_sistema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='hora_salida',
        ),
    ]
